# .github/workflows/actions.yml

name: Github Actions로 작업 병렬로 실행하기
# 실행 중지 - 참고용
# on: push

# needs가 없이 jobs가 여러개 있다면, multi-thread 병렬처리
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 작업의 1단계
        run: echo "첫 번째 작업의 첫 번째 단계입니다."
      - name: 첫 번째 작업의 2단계
        run: echo "첫 번째 작업의 두 번째 단계입니다."

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: 두 번째 작업의 1단계
        run: echo "두 번째 작업의 첫 번째 단계입니다."
      - name: 두 번째 작업의 2단계
        run: echo "두 번째 작업의 두 번째 단계입니다."
