# .github/workflows/actions.yml

name: Github Actions로 작업 병렬로 실행하기
# 실행 중지 - 참고용
# on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: 첫 번째 작업의 1단계
        run: echo "첫 번째 작업의 첫 번째 단계입니다."
      - name: 첫 번째 작업의 2단계
        run: echo "첫 번째 작업의 두 번째 단계입니다."

  second_job:
    runs-on: ubuntu-latest
    # needs: firest_job - 상단에 first_job의 작업이 끝난 후에 실행 (single-thread 동기 싱글 스레드 스타일)
    needs: first_job
    steps:
      - name: 두 번째 작업의 1단계
        run: echo "두 번째 작업의 첫 번째 단계입니다."
      - name: 두 번째 작업의 2단계
        run: echo "두 번째 작업의 두 번째 단계입니다."
