# .github/workflows/actions.yml

# 이름 짓기
name: Github Actions로 테스트 자동화하기
# 언제 이 작업을 실행할지 정의
# push: github에 push할 때마다 실행
on:
  pull_request:
    branches: main

# 어떤 직업
jobs:
  test:
    # 어떤 환경에서 실행할거야?
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        # actions 사용할 때 옵션 -> with
        with:
          node-version: 24

      - name: 의존성 (Library) 설치
        run: npm ci

      - name: 테스트 실행하기
        run: npm run test
